import { Transform } from 'class-transformer';
import {
  IsString,
  IsNotEmpty,
  MinLength,
  MaxLength,
  IsOptional,
  ArrayMaxSize,
  IsArray,
} from 'class-validator';

/**
 * CreateNoteDto
 *
 * Data Transfer Object for creating a new note.
 * Defines what fields the client must/can send when creating a note.
 *
 * Notice: NO id, createdAt, updatedAt - these are generated by the server!
 */
export class CreateNoteDto {
  /**
   * Note title
   * Required field
   *
   * Example: "React useEffect Hook"
   */
  @Transform(({ value }) => value.trim())
  @IsString({ message: 'Title must be a string' })
  @IsNotEmpty({ message: 'Title cannot be empty' })
  @MinLength(1, { message: 'Title must be at least 1 character long' })
  @MaxLength(200, {
    message: 'Title must be no longer than 200 characters',
  })
  title: string;

  /**
   * Note content/body
   * Required field
   * Can be multi-line
   *
   * Example: "useEffect(() => { ... }, [deps])"
   */
  @IsString({ message: 'Content must be a string' })
  @IsNotEmpty({ message: 'Content cannot be empty' })
  @MinLength(1, { message: 'Content must be at least 1 character long' })
  @MaxLength(5000, { message: 'Content must be no longer than 5000 characters' })
  content: string;

  /**
   * Tags for categorization
   * Optional field, defaults to empty array
   *
   * Example: ["react", "hooks", "frontend"]
   */
  @IsOptional()
  @IsArray({ message: 'Tags must be an array' })
  @ArrayMaxSize(10, { message: 'You can add up to 10 tags' })
  @IsString({ each: true, message: 'Tag must be a string' })
  @MaxLength(50, { each: true, message: 'Tag must be no longer than 50 characters' })
  tags?: string[];
}
